CREATE TABLE IF NOT EXISTS `calendar_comment` (
  `com_id` int(11) NOT NULL auto_increment,
  `com_cal_id` int(11) NOT NULL,
  `com_active` tinyint(1) default NULL,
  `com_name` varchar(50) default '',
  `com_email` varchar(50) default NULL,
  `com_text` text,
  `com_ip` varchar(50) default NULL,
  `com_date` datetime default NULL,
  `com_create` datetime default NULL,
  `com_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`com_id`),
  KEY `com_cal_id` (`com_cal_id`,`com_active`)
) ENGINE=MyISAM AUTO_INCREMENT=111 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar_settings` (
  `cal_id` mediumint(8) NOT NULL auto_increment,
  `cal_display` tinyint(1) default '1',
  `cal_history` date default NULL,
  `cal_history_comment` varchar(100) default NULL,
  `cal_image_width` int(11) default NULL,
  `cal_image_height` int(11) default NULL,
  `cal_image_max_width` int(11) default NULL,
  `cal_rows` int(11) default NULL,
  `cal_date_format` varchar(25) default '%A %d %B %Y',
  `cal_template` text,
  `cal_detail_img` tinyint(4) default NULL,
  `cal_comment_order_asc` tinyint(4) default NULL,
  `cal_comment` tinyint(4) default NULL,
  `cal_comment_notify` tinyint(4) default NULL,
  `cal_comment_title` varchar(255) default NULL,
  `cal_comment_display` int(11) default NULL,
  `cal_comment_width` int(11) default NULL,
  `cal_cap_name` varchar(100) default NULL,
  `cal_cap_email` varchar(50) default NULL,
  `cal_cap_desc` varchar(100) default NULL,
  `cal_cap_submit` varchar(100) default NULL,
  `cal_cap_back` varchar(100) default NULL,
  `cal_cap_detail` varchar(100) default NULL,
  `cal_group` tinyint(1) default '0',
  `cal_usr_id` mediumint(9) NOT NULL default '0',
  `cal_own_id` mediumint(9) default NULL,
  `cal_create` datetime default NULL,
  `cal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`cal_id`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar` (
  `cal_id` mediumint(8) NOT NULL auto_increment,
  `cal_tree_id` mediumint(9) NOT NULL default '0',
  `cal_tag` varchar(100) default NULL,
  `cal_active` tinyint(1) default '1',
  `cal_start` date default NULL,
  `cal_stop` date default NULL,
  `cal_start_time` varchar(50) default NULL,
  `cal_stop_time` varchar(50) default NULL,
  `cal_name` varchar(100) default NULL,
  `cal_intro` varchar(255) default NULL,
  `cal_text` text,
  `cal_image` varchar(255) default NULL,
  `cal_thumbnail` varchar(255) default NULL,
  `cal_img_x` int(11) default NULL,
  `cal_img_y` int(11) default NULL,
  `cal_img_width` int(11) default '0',
  `cal_img_height` int(11) default '0',
  `cal_count` int(11) default '0',
  `cal_usr_id` mediumint(9) NOT NULL default '0',
  `cal_own_id` mediumint(9) default NULL,
  `cal_create` datetime default NULL,
  `cal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`cal_id`),
  KEY `idx_tree` (`cal_tree_id`,`cal_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=31 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar_overview_settings` (
  `set_tree_id` int(11) NOT NULL,
  `set_tag` varchar(25) NOT NULL,
  `set_display` int(11) default NULL,
  `set_history` date default NULL,
  `set_history_comment` varchar(100) default NULL,
  `set_group` tinyint(1) default '0',
  `set_image_width` int(11) default '0',
  `set_image_height` int(11) default '0',
  `set_image_max_width` int(11) default '0',
  `set_rows` int(11) default '0',
  `set_date_format` varchar(25) default '%A %d %B %Y',
  `set_template` text,
  `set_detail_img` tinyint(4) default '0',
  `set_comment_order_asc` tinyint(1) default '1',
  `set_comment` tinyint(1) default '1',
  `set_comment_notify` tinyint(1) default '1',
  `set_comment_title` varchar(255) default NULL,
  `set_comment_display` int(11) default '1',
  `set_comment_width` int(11) default '50',
  `set_cap_name` varchar(50) default NULL,
  `set_cap_email` varchar(50) default NULL,
  `set_cap_desc` varchar(50) default NULL,
  `set_cap_submit` varchar(50) default NULL,
  `set_cap_back` varchar(25) default NULL,
  `set_cap_detail` varchar(25) default NULL,
  `set_usr_id` int(11) default NULL,
  `set_own_id` int(11) default NULL,
  `set_create` datetime default NULL,
  `set_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`set_tree_id`,`set_tag`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar_attachment` (
  `att_id` mediumint(8) NOT NULL auto_increment,
  `att_cal_id` mediumint(9) NOT NULL default '0',
  `att_weight` int(11) default '10',
  `att_active` tinyint(1) default '1',
  `att_name` varchar(100) default NULL,
  `att_file` varchar(255) default NULL,
  `att_usr_id` mediumint(9) NOT NULL default '0',
  `att_own_id` mediumint(9) default NULL,
  `att_create` datetime default NULL,
  `att_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`att_id`),
  KEY `idx_att_cal_id` (`att_cal_id`)
) ENGINE=MyISAM AUTO_INCREMENT=62 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar_archive` (
  `cal_tree_id` mediumint(9) NOT NULL default '0',
  `cal_tag` varchar(100) NOT NULL,
  `cal_start` date default NULL,
  `cal_stop` date default NULL,
  `cal_rows` tinyint(1) default '20',
  `cal_date_format` varchar(25) default '%d %B %Y',
  `cal_display` tinyint(1) default '3',
  `cal_group` tinyint(1) default '0',
  `cal_cap_detail` varchar(50) default NULL,
  `cal_usr_id` mediumint(9) NOT NULL default '0',
  `cal_own_id` mediumint(9) default NULL,
  `cal_create` datetime default NULL,
  `cal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`cal_tree_id`,`cal_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar_image` (
  `img_id` mediumint(9) NOT NULL auto_increment,
  `img_cal_id` mediumint(9) NOT NULL,
  `img_weight` int(11) default NULL,
  `img_active` tinyint(1) default '1',
  `img_name` varchar(100) default NULL,
  `img_thumbnail` varchar(255) default NULL,
  `img_image` varchar(255) default NULL,
  `img_img_x` int(11) default NULL,
  `img_img_y` int(11) default NULL,
  `img_img_width` int(11) default NULL,
  `img_img_height` int(11) default NULL,
  `img_usr_id` mediumint(9) default NULL,
  `img_own_id` mediumint(9) default NULL,
  `img_create` datetime default NULL,
  `img_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`img_id`),
  KEY `img_cal_id` (`img_cal_id`,`img_active`)
) ENGINE=MyISAM AUTO_INCREMENT=33 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar_tree_ref` (
  `cal_tree_id` mediumint(9) NOT NULL default '0',
  `cal_tag` varchar(100) NOT NULL,
  `cal_ref_tree_id` mediumint(9) NOT NULL default '0',
  `cal_usr_id` mediumint(9) NOT NULL default '0',
  `cal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`cal_tree_id`,`cal_tag`,`cal_ref_tree_id`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `calendar_headlines` (
  `cal_tree_id` mediumint(9) NOT NULL default '0',
  `cal_tag` varchar(100) NOT NULL,
  `cal_name` varchar(100) default NULL,
  `cal_rows` int(11) default '5',
  `cal_date_format` varchar(25) default '%d %B %Y',
  `cal_display` tinyint(1) default '3',
  `cal_group` tinyint(1) default '0',
  `cal_cap_detail` varchar(50) default NULL,
  `cal_usr_id` mediumint(9) NOT NULL default '0',
  `cal_own_id` mediumint(9) default NULL,
  `cal_create` datetime default NULL,
  `cal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`cal_tree_id`,`cal_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
