CREATE TABLE IF NOT EXISTS `news_headlines` (
  `news_tree_id` mediumint(9) NOT NULL default '0',
  `news_tag` varchar(100) NOT NULL,
  `news_name` varchar(100) default NULL,
  `news_rows` int(11) default '5',
  `news_date_format` varchar(25) default '%d %B %Y',
  `news_display` tinyint(1) default '1',
  `news_cap_detail` varchar(50) default NULL,
  `news_usr_id` mediumint(9) NOT NULL default '0',
  `news_own_id` mediumint(9) default NULL,
  `news_create` datetime default NULL,
  `news_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`news_tree_id`,`news_tag`),
  KEY `news_tree_id` (`news_tree_id`,`news_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news_tree_ref` (
  `news_tree_id` mediumint(9) NOT NULL default '0',
  `news_tag` varchar(100) NOT NULL,
  `news_ref_tree_id` mediumint(9) NOT NULL default '0',
  `news_usr_id` mediumint(9) NOT NULL default '0',
  `news_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`news_tree_id`,`news_tag`,`news_ref_tree_id`),
  KEY `news_tree_id` (`news_tree_id`,`news_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news_attachment` (
  `att_id` mediumint(8) NOT NULL auto_increment,
  `att_news_id` mediumint(9) NOT NULL default '0',
  `att_weight` int(11) default '10',
  `att_active` tinyint(1) default '1',
  `att_name` varchar(100) default NULL,
  `att_file` varchar(255) default NULL,
  `att_usr_id` mediumint(9) NOT NULL default '0',
  `att_own_id` mediumint(9) default NULL,
  `att_create` datetime default NULL,
  `att_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`att_id`),
  KEY `idx_att_news_id` (`att_news_id`)
) ENGINE=MyISAM AUTO_INCREMENT=40 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news_archive` (
  `news_tree_id` mediumint(9) NOT NULL default '0',
  `news_tag` varchar(100) NOT NULL,
  `news_online` date default NULL,
  `news_offline` date default NULL,
  `news_usr_id` mediumint(9) NOT NULL default '0',
  `news_own_id` mediumint(9) default NULL,
  `news_create` datetime default NULL,
  `news_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`news_tree_id`,`news_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news_settings` (
  `news_id` mediumint(8) NOT NULL auto_increment,
  `news_image_width` int(11) default NULL,
  `news_image_height` int(11) default NULL,
  `news_image_max_width` int(11) default NULL,
  `news_display` tinyint(1) default '1',
  `news_rows` int(11) default NULL,
  `news_date_format` varchar(25) default '%A %d %B %Y',
  `news_template` text,
  `news_detail_img` tinyint(4) default NULL,
  `news_comment_order_asc` tinyint(4) default NULL,
  `news_comment` tinyint(4) default NULL,
  `news_comment_notify` tinyint(4) default NULL,
  `news_comment_title` varchar(255) default NULL,
  `news_comment_display` int(11) default NULL,
  `news_comment_width` int(11) default NULL,
  `news_cap_name` varchar(100) default NULL,
  `news_cap_email` varchar(50) default NULL,
  `news_cap_desc` varchar(100) default NULL,
  `news_cap_submit` varchar(100) default NULL,
  `news_cap_back` varchar(100) default NULL,
  `news_cap_detail` varchar(100) default NULL,
  `news_usr_id` mediumint(9) NOT NULL default '0',
  `news_own_id` mediumint(9) default NULL,
  `news_create` datetime default NULL,
  `news_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`news_id`)
) ENGINE=MyISAM AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news_overview_settings` (
  `set_tree_id` mediumint(9) NOT NULL default '0',
  `set_tag` varchar(100) NOT NULL default '',
  `set_display` tinyint(1) default '1',
  `set_image_width` int(11) default '0',
  `set_image_height` int(11) default '0',
  `set_image_max_width` int(11) default '0',
  `set_rows` int(11) default '0',
  `set_date_format` varchar(25) default NULL,
  `set_template` text,
  `set_detail_img` tinyint(4) default '0',
  `set_comment_order_asc` tinyint(1) default '1',
  `set_comment` tinyint(1) default '1',
  `set_comment_notify` tinyint(1) default '1',
  `set_comment_title` varchar(255) default '',
  `set_comment_display` int(11) default '1',
  `set_comment_width` int(11) default '50',
  `set_cap_name` varchar(100) default NULL,
  `set_cap_email` varchar(50) default NULL,
  `set_cap_desc` varchar(100) default NULL,
  `set_cap_submit` varchar(100) default NULL,
  `set_cap_back` varchar(100) default NULL,
  `set_cap_detail` varchar(100) default NULL,
  `set_usr_id` mediumint(9) NOT NULL default '0',
  `set_own_id` mediumint(9) default NULL,
  `set_create` datetime default NULL,
  `set_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`set_tree_id`,`set_tag`),
  KEY `set_tree_id` (`set_tree_id`,`set_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news` (
  `news_id` mediumint(8) NOT NULL auto_increment,
  `news_tree_id` mediumint(9) NOT NULL default '0',
  `news_tag` varchar(100) default NULL,
  `news_active` tinyint(1) default '1',
  `news_online` date default NULL,
  `news_date` date default NULL,
  `news_offline` date default NULL,
  `news_name` varchar(100) default NULL,
  `news_intro` varchar(255) default NULL,
  `news_text` text,
  `news_image` varchar(255) default NULL,
  `news_thumbnail` varchar(255) default NULL,
  `news_img_x` int(11) default NULL,
  `news_img_y` int(11) default NULL,
  `news_img_width` int(11) default '0',
  `news_img_height` int(11) default '0',
  `news_count` int(11) default '0',
  `news_usr_id` mediumint(9) NOT NULL default '0',
  `news_own_id` mediumint(9) default NULL,
  `news_create` datetime default NULL,
  `news_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`news_id`),
  KEY `idx_tree` (`news_tree_id`,`news_tag`),
  KEY `news_tree_id` (`news_tree_id`,`news_tag`,`news_active`,`news_online`,`news_offline`)
) ENGINE=MyISAM AUTO_INCREMENT=36 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news_image` (
  `img_id` mediumint(9) NOT NULL auto_increment,
  `img_news_id` mediumint(9) NOT NULL,
  `img_weight` int(11) default NULL,
  `img_active` tinyint(1) default '1',
  `img_name` varchar(100) default NULL,
  `img_thumbnail` varchar(255) default NULL,
  `img_image` varchar(255) default NULL,
  `img_img_x` int(11) default NULL,
  `img_img_y` int(11) default NULL,
  `img_img_width` int(11) default NULL,
  `img_img_height` int(11) default NULL,
  `img_usr_id` mediumint(9) default NULL,
  `img_own_id` mediumint(9) default NULL,
  `img_create` datetime default NULL,
  `img_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`img_id`),
  KEY `img_news_id` (`img_news_id`,`img_active`)
) ENGINE=MyISAM AUTO_INCREMENT=31 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `news_comment` (
  `com_id` int(11) NOT NULL auto_increment,
  `com_news_id` int(11) NOT NULL,
  `com_active` tinyint(1) default NULL,
  `com_name` varchar(50) default '',
  `com_email` varchar(50) default NULL,
  `com_text` text,
  `com_ip` varchar(50) default NULL,
  `com_date` datetime default NULL,
  `com_create` datetime default NULL,
  `com_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`com_id`),
  KEY `com_news_id` (`com_news_id`,`com_active`)
) ENGINE=MyISAM AUTO_INCREMENT=109 DEFAULT CHARSET=latin1;
