CREATE TABLE IF NOT EXISTS `gallery_settings` (
  `gal_id` mediumint(8) NOT NULL auto_increment,
  `gal_display` tinyint(1) default '1',
  `gal_display_overview` tinyint(4) default '0',
  `gal_image_width` int(11) default NULL,
  `gal_image_height` int(11) default NULL,
  `gal_image_max_width` int(11) default NULL,
  `gal_rows` int(11) default NULL,
  `gal_date_format` varchar(25) default '%A %d %B %Y',
  `gal_template` text,
  `gal_detail_img` tinyint(4) default NULL,
  `gal_comment_order_asc` tinyint(4) default NULL,
  `gal_comment` tinyint(4) default NULL,
  `gal_comment_notify` tinyint(4) default NULL,
  `gal_comment_title` varchar(255) default NULL,
  `gal_comment_display` int(11) default NULL,
  `gal_comment_width` int(11) default NULL,
  `gal_cap_name` varchar(100) default NULL,
  `gal_cap_email` varchar(50) default NULL,
  `gal_cap_desc` varchar(100) default NULL,
  `gal_cap_submit` varchar(100) default NULL,
  `gal_cap_previous` varchar(100) default NULL,
  `gal_cap_next` varchar(100) default NULL,
  `gal_cap_back` varchar(100) default NULL,
  `gal_cap_detail` varchar(100) default NULL,
  `gal_usr_id` mediumint(9) NOT NULL default '0',
  `gal_own_id` mediumint(9) default NULL,
  `gal_create` datetime default NULL,
  `gal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`gal_id`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `gallery` (
  `gal_id` mediumint(8) NOT NULL auto_increment,
  `gal_tree_id` mediumint(9) NOT NULL default '0',
  `gal_tag` varchar(100) default NULL,
  `gal_weight` int(11) default '0',
  `gal_active` tinyint(1) default '1',
  `gal_name` varchar(100) default NULL,
  `gal_description` varchar(255) default NULL,
  `gal_image` varchar(255) default NULL,
  `gal_thumbnail` varchar(255) default NULL,
  `gal_img_x` int(11) default NULL,
  `gal_img_y` int(11) default NULL,
  `gal_img_width` int(11) default '0',
  `gal_img_height` int(11) default '0',
  `gal_usr_id` mediumint(9) NOT NULL default '0',
  `gal_own_id` mediumint(9) default NULL,
  `gal_create` datetime default NULL,
  `gal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`gal_id`),
  KEY `idx_gal_tree_id` (`gal_tree_id`),
  KEY `gal_tree_id` (`gal_tree_id`,`gal_tag`,`gal_active`)
) ENGINE=MyISAM AUTO_INCREMENT=208 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `gallery_tree_ref` (
  `gal_tree_id` mediumint(9) NOT NULL default '0',
  `gal_tag` varchar(100) NOT NULL,
  `gal_ref_tree_id` mediumint(9) NOT NULL default '0',
  `gal_usr_id` mediumint(9) NOT NULL default '0',
  `gal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`gal_tree_id`,`gal_tag`,`gal_ref_tree_id`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `gallery_overview_settings` (
  `set_tree_id` mediumint(9) NOT NULL default '0',
  `set_tag` varchar(100) NOT NULL default '',
  `set_display` tinyint(1) default '1',
  `set_display_overview` tinyint(4) default '0',
  `set_image_width` int(11) default '0',
  `set_image_height` int(11) default '0',
  `set_image_max_width` int(11) default '0',
  `set_rows` int(11) default '0',
  `set_date_format` varchar(25) default NULL,
  `set_template` text,
  `set_detail_img` tinyint(4) default '0',
  `set_comment_order_asc` tinyint(1) default '1',
  `set_comment` tinyint(1) default '1',
  `set_comment_notify` tinyint(1) default '1',
  `set_comment_title` varchar(255) default '',
  `set_comment_display` int(11) default '1',
  `set_comment_width` int(11) default '50',
  `set_cap_name` varchar(100) default NULL,
  `set_cap_email` varchar(50) default NULL,
  `set_cap_desc` varchar(100) default NULL,
  `set_cap_submit` varchar(100) default NULL,
  `set_cap_previous` varchar(100) default NULL,
  `set_cap_next` varchar(100) default NULL,
  `set_cap_back` varchar(100) default NULL,
  `set_cap_detail` varchar(100) default NULL,
  `set_usr_id` mediumint(9) NOT NULL default '0',
  `set_own_id` mediumint(9) default NULL,
  `set_create` datetime default NULL,
  `set_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`set_tree_id`,`set_tag`),
  KEY `set_tree_id` (`set_tree_id`,`set_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=24 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `gallery_headlines` (
  `gal_tree_id` mediumint(9) NOT NULL default '0',
  `gal_tag` varchar(100) NOT NULL,
  `gal_name` varchar(100) default NULL,
  `gal_display` tinyint(1) default '1',
  `gal_display_order` tinyint(4) default NULL,
  `gal_rows` int(11) default '5',
  `gal_usr_id` mediumint(9) NOT NULL default '0',
  `gal_own_id` mediumint(9) default NULL,
  `gal_create` datetime default NULL,
  `gal_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`gal_tree_id`,`gal_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `gallery_comment` (
  `com_id` int(11) NOT NULL auto_increment,
  `com_gal_id` int(11) NOT NULL,
  `com_active` tinyint(1) default NULL,
  `com_name` varchar(50) default '',
  `com_email` varchar(50) default NULL,
  `com_text` text,
  `com_ip` varchar(50) default NULL,
  `com_date` datetime default NULL,
  `com_create` datetime default NULL,
  `com_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`com_id`),
  KEY `com_gal_id` (`com_gal_id`,`com_active`)
) ENGINE=MyISAM AUTO_INCREMENT=110 DEFAULT CHARSET=latin1;
