CREATE TABLE IF NOT EXISTS `form_record_item` (
  `item_id` mediumint(9) NOT NULL auto_increment,
  `item_rcd_id` mediumint(9) NOT NULL default '0',
  `item_elm_id` varchar(15) default '',
  `item_classname` varchar(25) default '',
  `item_weight` int(11) default '1',
  `item_name` varchar(100) default NULL,
  `item_value` text,
  PRIMARY KEY  (`item_id`),
  KEY `idx_item_tree_id` (`item_rcd_id`),
  KEY `item_rcd_id` (`item_rcd_id`)
) ENGINE=MyISAM AUTO_INCREMENT=540 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `form_settings` (
  `form_id` mediumint(9) NOT NULL auto_increment,
  `form_subject` varchar(100) NOT NULL,
  `form_from` varchar(100) default NULL,
  `form_to` varchar(100) default NULL,
  `form_caption` varchar(50) default '',
  `form_action` int(11) default '1',
  `form_mail_text` text,
  `form_templatefield` text,
  `form_mandatorysign` varchar(100) default NULL,
  `form_usr_id` int(11) default NULL,
  `form_own_id` int(11) default NULL,
  `form_create` datetime default NULL,
  `form_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`form_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `form_tree_settings` (
  `form_tree_id` mediumint(9) NOT NULL default '0',
  `form_tag` varchar(100) NOT NULL,
  `form_subject` varchar(100) NOT NULL,
  `form_from` varchar(100) default NULL,
  `form_to` varchar(100) default NULL,
  `form_caption` varchar(50) default '',
  `form_action` int(11) default '1',
  `form_mail_text` text,
  `form_ref_tree_id` mediumint(9) NOT NULL default '0',
  `form_optin_tree_id` int(11) default NULL,
  `form_templatefield` text,
  `form_mandatorysign` varchar(100) default NULL,
  `form_usr_id` mediumint(9) NOT NULL default '0',
  `form_own_id` mediumint(9) default NULL,
  `form_create` datetime default NULL,
  `form_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`form_tree_id`,`form_tag`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `form` (
  `form_id` mediumint(8) NOT NULL auto_increment,
  `form_tree_id` mediumint(9) NOT NULL default '0',
  `form_tag` varchar(100) default NULL,
  `form_type` varchar(25) NOT NULL,
  `form_active` tinyint(1) default '1',
  `form_weight` int(11) default '0',
  `form_mandatory` tinyint(1) default '1',
  `form_size` int(11) default '1',
  `form_name` varchar(255) default NULL,
  `form_description` text,
  `form_default` varchar(255) default NULL,
  `form_options` text,
  `form_usr_id` mediumint(9) NOT NULL default '0',
  `form_own_id` mediumint(9) default NULL,
  `form_create` datetime default NULL,
  `form_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`form_id`),
  KEY `idx_form_tree_id` (`form_tree_id`),
  KEY `idx_form_tag` (`form_tag`),
  KEY `form_tree_id` (`form_tree_id`,`form_tag`,`form_active`)
) ENGINE=MyISAM AUTO_INCREMENT=75 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `form_record` (
  `rcd_id` mediumint(8) NOT NULL auto_increment,
  `rcd_tree_id` mediumint(9) NOT NULL default '0',
  `rcd_tag` varchar(100) NOT NULL,
  `rcd_ip` varchar(20) default NULL,
  `rcd_host` varchar(100) default NULL,
  `rcd_client` varchar(100) default NULL,
  `rcd_optin` varchar(50) default NULL,
  `rcd_create` datetime default NULL,
  `rcd_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`rcd_id`),
  KEY `idx_rcd_tree_id` (`rcd_tree_id`),
  KEY `idx_rcd_tag` (`rcd_tag`),
  KEY `rcd_tree_id` (`rcd_tree_id`,`rcd_tag`,`rcd_optin`)
) ENGINE=MyISAM AUTO_INCREMENT=131 DEFAULT CHARSET=latin1;
