CREATE TABLE IF NOT EXISTS `banner` (
  `bnr_id` mediumint(8) NOT NULL auto_increment,
  `bnr_tree_id` mediumint(9) NOT NULL default '0',
  `bnr_tag` varchar(100) default NULL,
  `bnr_weight` int(11) default '10',
  `bnr_active` tinyint(1) default '1',
  `bnr_online` date default NULL,
  `bnr_offline` date default NULL,
  `bnr_name` varchar(100) default NULL,
  `bnr_image` varchar(255) default NULL,
  `bnr_image_temp` varchar(255) default NULL,
  `bnr_img_x` int(11) default '0',
  `bnr_img_y` int(11) default '0',
  `bnr_img_width` int(11) default '0',
  `bnr_img_height` int(11) default '0',
  `bnr_url` varchar(255) default NULL,
  `bnr_views` int(11) default '0',
  `bnr_clicks` int(11) default '0',
  `bnr_usr_id` mediumint(9) NOT NULL default '0',
  `bnr_own_id` mediumint(9) default NULL,
  `bnr_create` datetime default NULL,
  `bnr_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`bnr_id`),
  KEY `idx_bnr_tree_id` (`bnr_tree_id`)
) ENGINE=MyISAM AUTO_INCREMENT=45 DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `banner_settings` (
  `bnr_id` mediumint(8) NOT NULL auto_increment,
  `bnr_tree_id` mediumint(9) NOT NULL default '0',
  `bnr_tag` varchar(100) default NULL,
  `bnr_display` tinyint(1) default '1',
  `bnr_display_order` tinyint(4) default '1',
  `bnr_url` tinyint(1) default '0',
  `bnr_transition_speed` tinyint(1) default '1',
  `bnr_img_width` int(11) default NULL,
  `bnr_img_height` int(11) default NULL,
  `bnr_img_max_width` int(11) default '800',
  `bnr_image` varchar(255) default NULL,
  `bnr_usr_id` mediumint(9) NOT NULL default '0',
  `bnr_own_id` mediumint(9) default NULL,
  `bnr_create` datetime default NULL,
  `bnr_ts` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`bnr_id`)
) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;
